### ISSUE TITLE
Update unbuild_net.s with the latest version

### ISSUE THREAD

**Issue by ray-ngo** [ray-ngo/GEN2#3]
To update the script to work with the latest version

**Comment by cogtesting1** [comment]
@cogtesting2: Can you review my work before I make a pull request?

**Comment by cogtesting2** [comment]
@cogtesting1 : The code looks good. But revised the comment. Check it out 9b5bfbc9cc9393ae5d8363d9d769b8c176190faf

**Comment by cogtesting1** [comment]
@cogtesting2 : thanks
